# This file has been automatically generated by the script.
# Test case for Vectore load instructions.
.section .text
.global main
main:
    vadd.vv v3, v9, v10
    vadd.vv v15, v22, v19
    vadd.vv v26, v25, v2
    vadd.vv v15, v11, v31
    vadd.vv v14, v22, v21
    vadd.vv v20, v29, v10
    vadd.vv v18, v7, v0
    vadd.vv v10, v31, v7
    vadd.vv v21, v3, v6
    vadd.vv v22, v23, v26
    vadd.vv v20, v1, v28
    vadd.vv v3, v5, v7
    vadd.vv v29, v9, v28
    vadd.vv v15, v6, v21
    vadd.vv v10, v8, v1
    vadd.vx v21, v24, x9
    vadd.vx v25, v29, x30
    vadd.vx v3, v13, x3
    vadd.vx v14, v10, x4
    vadd.vx v24, v30, x23
    vadd.vx v4, v8, x31
    vadd.vx v19, v17, x14
    vadd.vx v18, v6, x16
    vadd.vx v2, v15, x6
    vadd.vx v25, v2, x23
    vadd.vx v23, v21, x1
    vadd.vx v8, v28, x20
    vadd.vx v7, v10, x16
    vadd.vx v29, v10, x31
    vadd.vx v24, v2, x18
    vadd.vi v0, v23, 8
    vadd.vi v29, v13, 8
    vadd.vi v17, v7, 8
    vadd.vi v16, v27, 8
    vadd.vi v1, v4, 8
    vadd.vi v24, v16, 8
    vadd.vi v15, v24, 8
    vadd.vi v10, v20, 8
    vadd.vi v16, v16, 8
    vadd.vi v29, v21, 8
    vadd.vi v29, v16, 8
    vadd.vi v2, v28, 8
    vadd.vi v27, v20, 8
    vadd.vi v28, v7, 8
    vadd.vi v28, v8, 8
    vsub.vv v10, v29, v25
    vsub.vv v28, v26, v11
    vsub.vv v25, v15, v19
    vsub.vv v19, v21, v25
    vsub.vv v20, v9, v27
    vsub.vv v11, v19, v13
    vsub.vv v12, v31, v23
    vsub.vv v25, v20, v30
    vsub.vv v5, v8, v18
    vsub.vv v14, v18, v21
    vsub.vv v10, v15, v21
    vsub.vv v27, v29, v25
    vsub.vv v1, v19, v2
    vsub.vv v17, v8, v16
    vsub.vv v5, v24, v30
    vsub.vx v12, v15, x11
    vsub.vx v17, v0, x20
    vsub.vx v22, v25, x15
    vsub.vx v7, v13, x2
    vsub.vx v17, v3, x6
    vsub.vx v30, v3, x8
    vsub.vx v13, v26, x31
    vsub.vx v8, v22, x20
    vsub.vx v24, v18, x1
    vsub.vx v10, v16, x22
    vsub.vx v5, v14, x12
    vsub.vx v4, v0, x7
    vsub.vx v24, v9, x5
    vsub.vx v27, v9, x18
    vsub.vx v30, v7, x23
    vrsub.vx v29, v5, x15
    vrsub.vx v16, v13, x8
    vrsub.vx v16, v16, x3
    vrsub.vx v11, v26, x29
    vrsub.vx v21, v7, x28
    vrsub.vx v19, v25, x31
    vrsub.vx v25, v2, x3
    vrsub.vx v20, v2, x21
    vrsub.vx v25, v26, x28
    vrsub.vx v23, v6, x19
    vrsub.vx v26, v22, x17
    vrsub.vx v5, v22, x10
    vrsub.vx v26, v12, x9
    vrsub.vx v1, v24, x5
    vrsub.vx v21, v9, x18
    vrsub.vi v10, v2, 8
    vrsub.vi v27, v13, 8
    vrsub.vi v9, v28, 8
    vrsub.vi v25, v2, 8
    vrsub.vi v5, v18, 8
    vrsub.vi v22, v25, 8
    vrsub.vi v19, v29, 8
    vrsub.vi v12, v27, 8
    vrsub.vi v29, v4, 8
    vrsub.vi v6, v10, 8
    vrsub.vi v31, v15, 8
    vrsub.vi v26, v1, 8
    vrsub.vi v27, v13, 8
    vrsub.vi v30, v7, 8
    vrsub.vi v29, v27, 8
    vminu.vv v0, v0, v15
    vminu.vv v12, v1, v16
    vminu.vv v11, v10, v21
    vminu.vv v16, v7, v26
    vminu.vv v1, v4, v29
    vminu.vv v1, v21, v2
    vminu.vv v10, v17, v11
    vminu.vv v29, v20, v14
    vminu.vv v30, v8, v11
    vminu.vv v0, v5, v26
    vminu.vv v15, v7, v16
    vminu.vv v13, v3, v23
    vminu.vv v15, v15, v13
    vminu.vv v2, v20, v2
    vminu.vv v28, v15, v19
    vminu.vx v12, v19, x14
    vminu.vx v2, v17, x18
    vminu.vx v30, v26, x0
    vminu.vx v22, v0, x23
    vminu.vx v5, v0, x18
    vminu.vx v10, v1, x24
    vminu.vx v19, v20, x24
    vminu.vx v17, v22, x4
    vminu.vx v30, v25, x9
    vminu.vx v13, v10, x10
    vminu.vx v23, v29, x9
    vminu.vx v8, v10, x28
    vminu.vx v3, v17, x31
    vminu.vx v27, v30, x12
    vminu.vx v24, v28, x17
    vmin.vv v2, v20, v20
    vmin.vv v16, v5, v16
    vmin.vv v23, v16, v0
    vmin.vv v4, v10, v31
    vmin.vv v26, v25, v18
    vmin.vv v25, v23, v4
    vmin.vv v25, v20, v4
    vmin.vv v5, v1, v28
    vmin.vv v17, v4, v17
    vmin.vv v16, v14, v17
    vmin.vv v6, v13, v15
    vmin.vv v8, v27, v31
    vmin.vv v30, v9, v24
    vmin.vv v15, v18, v7
    vmin.vv v31, v20, v1
    vmin.vx v5, v0, x20
    vmin.vx v28, v12, x9
    vmin.vx v21, v6, x2
    vmin.vx v24, v27, x22
    vmin.vx v6, v6, x6
    vmin.vx v24, v2, x0
    vmin.vx v12, v18, x19
    vmin.vx v19, v1, x6
    vmin.vx v4, v23, x9
    vmin.vx v14, v0, x31
    vmin.vx v23, v26, x30
    vmin.vx v16, v2, x8
    vmin.vx v2, v15, x25
    vmin.vx v24, v22, x15
    vmin.vx v2, v31, x7
    vmaxu.vv v11, v10, v15
    vmaxu.vv v22, v25, v20
    vmaxu.vv v5, v14, v25
    vmaxu.vv v12, v16, v31
    vmaxu.vv v22, v13, v8
    vmaxu.vv v4, v28, v7
    vmaxu.vv v3, v16, v3
    vmaxu.vv v14, v31, v10
    vmaxu.vv v5, v22, v2
    vmaxu.vv v27, v1, v3
    vmaxu.vv v26, v21, v31
    vmaxu.vv v18, v0, v17
    vmaxu.vv v10, v0, v16
    vmaxu.vv v2, v2, v27
    vmaxu.vv v23, v16, v30
    vmaxu.vx v24, v0, x3
    vmaxu.vx v3, v7, x2
    vmaxu.vx v22, v20, x20
    vmaxu.vx v14, v29, x7
    vmaxu.vx v25, v20, x25
    vmaxu.vx v22, v27, x5
    vmaxu.vx v27, v6, x2
    vmaxu.vx v5, v5, x0
    vmaxu.vx v21, v19, x21
    vmaxu.vx v9, v6, x18
    vmaxu.vx v30, v29, x21
    vmaxu.vx v0, v23, x17
    vmaxu.vx v3, v23, x14
    vmaxu.vx v24, v6, x10
    vmaxu.vx v16, v15, x9
    vmax.vv v9, v2, v17
    vmax.vv v4, v25, v10
    vmax.vv v11, v20, v9
    vmax.vv v10, v6, v15
    vmax.vv v2, v10, v20
    vmax.vv v12, v30, v21
    vmax.vv v19, v14, v19
    vmax.vv v8, v12, v18
    vmax.vv v28, v27, v31
    vmax.vv v31, v6, v12
    vmax.vv v16, v20, v8
    vmax.vv v19, v9, v29
    vmax.vv v6, v8, v18
    vmax.vv v24, v17, v25
    vmax.vv v28, v9, v14
    vmax.vx v0, v16, x1
    vmax.vx v8, v16, x0
    vmax.vx v5, v26, x8
    vmax.vx v25, v31, x31
    vmax.vx v30, v19, x22
    vmax.vx v8, v16, x3
    vmax.vx v20, v20, x11
    vmax.vx v10, v2, x12
    vmax.vx v1, v3, x14
    vmax.vx v28, v17, x4
    vmax.vx v0, v16, x7
    vmax.vx v25, v22, x8
    vmax.vx v23, v11, x24
    vmax.vx v17, v3, x13
    vmax.vx v4, v26, x23
    vand.vv v14, v23, v19
    vand.vv v24, v24, v24
    vand.vv v1, v16, v26
    vand.vv v10, v3, v21
    vand.vv v26, v5, v16
    vand.vv v11, v2, v10
    vand.vv v8, v21, v11
    vand.vv v23, v2, v28
    vand.vv v1, v4, v11
    vand.vv v21, v4, v20
    vand.vv v1, v6, v16
    vand.vv v30, v14, v23
    vand.vv v8, v11, v0
    vand.vv v4, v19, v22
    vand.vv v21, v20, v30
    vand.vx v3, v29, x26
    vand.vx v2, v19, x3
    vand.vx v8, v28, x8
    vand.vx v18, v14, x17
    vand.vx v13, v27, x16
    vand.vx v21, v13, x0
    vand.vx v18, v20, x20
    vand.vx v21, v23, x30
    vand.vx v19, v3, x23
    vand.vx v12, v30, x29
    vand.vx v7, v9, x13
    vand.vx v12, v24, x30
    vand.vx v0, v31, x3
    vand.vx v21, v22, x23
    vand.vx v16, v28, x23
    vand.vi v25, v1, 8
    vand.vi v5, v19, 8
    vand.vi v31, v7, 8
    vand.vi v19, v8, 8
    vand.vi v6, v12, 8
    vand.vi v28, v11, 8
    vand.vi v1, v24, 8
    vand.vi v15, v11, 8
    vand.vi v10, v26, 8
    vand.vi v28, v22, 8
    vand.vi v9, v7, 8
    vand.vi v9, v23, 8
    vand.vi v18, v0, 8
    vand.vi v26, v12, 8
    vand.vi v29, v2, 8
    vor.vv v10, v0, v15
    vor.vv v22, v10, v12
    vor.vv v17, v3, v24
    vor.vv v11, v6, v17
    vor.vv v27, v18, v2
    vor.vv v3, v14, v5
    vor.vv v11, v23, v7
    vor.vv v12, v16, v17
    vor.vv v14, v30, v31
    vor.vv v25, v31, v14
    vor.vv v20, v31, v18
    vor.vv v11, v4, v14
    vor.vv v7, v17, v5
    vor.vv v4, v10, v0
    vor.vv v23, v4, v15
    vor.vx v18, v11, x21
    vor.vx v30, v9, x28
    vor.vx v23, v2, x13
    vor.vx v28, v21, x15
    vor.vx v29, v0, x10
    vor.vx v10, v28, x12
    vor.vx v1, v6, x9
    vor.vx v6, v9, x24
    vor.vx v12, v13, x14
    vor.vx v22, v31, x24
    vor.vx v30, v29, x27
    vor.vx v29, v0, x10
    vor.vx v3, v14, x26
    vor.vx v27, v0, x28
    vor.vx v19, v28, x1
    vor.vi v17, v4, 8
    vor.vi v16, v4, 8
    vor.vi v27, v6, 8
    vor.vi v20, v14, 8
    vor.vi v5, v29, 8
    vor.vi v24, v28, 8
    vor.vi v1, v24, 8
    vor.vi v14, v22, 8
    vor.vi v8, v15, 8
    vor.vi v11, v12, 8
    vor.vi v13, v21, 8
    vor.vi v22, v18, 8
    vor.vi v23, v2, 8
    vor.vi v18, v26, 8
    vor.vi v0, v0, 8
    vxor.vv v17, v8, v30
    vxor.vv v3, v10, v27
    vxor.vv v16, v11, v29
    vxor.vv v24, v22, v3
    vxor.vv v15, v24, v20
    vxor.vv v6, v21, v0
    vxor.vv v30, v13, v20
    vxor.vv v30, v15, v18
    vxor.vv v23, v6, v5
    vxor.vv v11, v0, v25
    vxor.vv v3, v30, v17
    vxor.vv v31, v24, v29
    vxor.vv v8, v24, v19
    vxor.vv v0, v9, v31
    vxor.vv v12, v28, v12
    vxor.vx v25, v13, x9
    vxor.vx v4, v14, x1
    vxor.vx v19, v25, x14
    vxor.vx v15, v19, x11
    vxor.vx v25, v6, x0
    vxor.vx v17, v29, x21
    vxor.vx v17, v2, x2
    vxor.vx v4, v12, x28
    vxor.vx v2, v9, x14
    vxor.vx v3, v1, x2
    vxor.vx v25, v5, x16
    vxor.vx v25, v17, x8
    vxor.vx v5, v16, x18
    vxor.vx v20, v1, x7
    vxor.vx v23, v30, x4
    vxor.vi v5, v1, 8
    vxor.vi v28, v0, 8
    vxor.vi v2, v7, 8
    vxor.vi v0, v7, 8
    vxor.vi v2, v18, 8
    vxor.vi v24, v25, 8
    vxor.vi v6, v21, 8
    vxor.vi v9, v2, 8
    vxor.vi v4, v10, 8
    vxor.vi v7, v29, 8
    vxor.vi v0, v7, 8
    vxor.vi v13, v29, 8
    vxor.vi v25, v17, 8
    vxor.vi v15, v19, 8
    vxor.vi v22, v29, 8
    vrgather.vv v26, v22, v14
    vrgather.vv v12, v2, v7
    vrgather.vv v22, v22, v24
    vrgather.vv v13, v24, v24
    vrgather.vv v27, v10, v0
    vrgather.vv v15, v12, v26
    vrgather.vv v30, v19, v13
    vrgather.vv v0, v21, v28
    vrgather.vv v30, v29, v29
    vrgather.vv v24, v3, v0
    vrgather.vv v15, v10, v6
    vrgather.vv v12, v7, v25
    vrgather.vv v20, v9, v12
    vrgather.vv v21, v8, v20
    vrgather.vv v5, v0, v22
    vrgather.vx v17, v7, x13
    vrgather.vx v1, v24, x27
    vrgather.vx v17, v2, x13
    vrgather.vx v4, v21, x25
    vrgather.vx v3, v9, x8
    vrgather.vx v9, v11, x13
    vrgather.vx v23, v11, x12
    vrgather.vx v4, v1, x26
    vrgather.vx v23, v31, x30
    vrgather.vx v16, v13, x18
    vrgather.vx v9, v15, x2
    vrgather.vx v1, v27, x27
    vrgather.vx v13, v25, x10
    vrgather.vx v7, v18, x6
    vrgather.vx v14, v1, x19
    vrgather.vi v4, v15, 8
    vrgather.vi v25, v30, 8
    vrgather.vi v29, v25, 8
    vrgather.vi v19, v0, 8
    vrgather.vi v22, v18, 8
    vrgather.vi v28, v15, 8
    vrgather.vi v19, v30, 8
    vrgather.vi v1, v14, 8
    vrgather.vi v30, v9, 8
    vrgather.vi v0, v21, 8
    vrgather.vi v18, v26, 8
    vrgather.vi v29, v9, 8
    vrgather.vi v22, v29, 8
    vrgather.vi v14, v14, 8
    vrgather.vi v11, v9, 8
    vslideup.vx v24, v30, x13
    vslideup.vx v23, v28, x3
    vslideup.vx v11, v16, x16
    vslideup.vx v18, v3, x31
    vslideup.vx v26, v30, x17
    vslideup.vx v31, v13, x21
    vslideup.vx v5, v2, x24
    vslideup.vx v25, v13, x4
    vslideup.vx v9, v25, x16
    vslideup.vx v29, v4, x15
    vslideup.vx v15, v19, x29
    vslideup.vx v21, v6, x7
    vslideup.vx v3, v23, x29
    vslideup.vx v9, v3, x7
    vslideup.vx v30, v2, x22
    vslideup.vi v5, v16, 8
    vslideup.vi v16, v14, 8
    vslideup.vi v30, v0, 8
    vslideup.vi v28, v29, 8
    vslideup.vi v16, v29, 8
    vslideup.vi v9, v25, 8
    vslideup.vi v12, v18, 8
    vslideup.vi v16, v24, 8
    vslideup.vi v24, v2, 8
    vslideup.vi v6, v28, 8
    vslideup.vi v25, v2, 8
    vslideup.vi v15, v29, 8
    vslideup.vi v15, v12, 8
    vslideup.vi v0, v22, 8
    vslideup.vi v17, v24, 8
    vrgatherei16.vv v14, v23, v23
    vrgatherei16.vv v24, v30, v18
    vrgatherei16.vv v30, v15, v12
    vrgatherei16.vv v21, v22, v13
    vrgatherei16.vv v9, v5, v1
    vrgatherei16.vv v7, v12, v18
    vrgatherei16.vv v16, v29, v21
    vrgatherei16.vv v10, v22, v26
    vrgatherei16.vv v27, v13, v3
    vrgatherei16.vv v18, v6, v14
    vrgatherei16.vv v20, v27, v31
    vrgatherei16.vv v12, v26, v26
    vrgatherei16.vv v25, v19, v14
    vrgatherei16.vv v2, v30, v7
    vrgatherei16.vv v22, v1, v29
    vslidedown.vx v8, v3, x9
    vslidedown.vx v15, v18, x23
    vslidedown.vx v0, v13, x22
    vslidedown.vx v10, v9, x2
    vslidedown.vx v16, v8, x18
    vslidedown.vx v9, v25, x21
    vslidedown.vx v28, v26, x0
    vslidedown.vx v17, v13, x12
    vslidedown.vx v4, v17, x25
    vslidedown.vx v5, v0, x24
    vslidedown.vx v15, v1, x12
    vslidedown.vx v1, v23, x12
    vslidedown.vx v2, v30, x31
    vslidedown.vx v9, v3, x3
    vslidedown.vx v24, v0, x25
    vslidedown.vi v30, v19, 8
    vslidedown.vi v16, v2, 8
    vslidedown.vi v11, v15, 8
    vslidedown.vi v12, v16, 8
    vslidedown.vi v16, v27, 8
    vslidedown.vi v20, v5, 8
    vslidedown.vi v9, v31, 8
    vslidedown.vi v8, v29, 8
    vslidedown.vi v7, v31, 8
    vslidedown.vi v14, v13, 8
    vslidedown.vi v6, v6, 8
    vslidedown.vi v30, v17, 8
    vslidedown.vi v29, v29, 8
    vslidedown.vi v11, v19, 8
    vslidedown.vi v15, v23, 8
    vadc.vvm v19, v15, v16, v0
    vadc.vvm v26, v9, v5, v0
    vadc.vvm v6, v16, v31, v0
    vadc.vvm v24, v10, v16, v0
    vadc.vvm v18, v17, v12, v0
    vadc.vvm v8, v8, v2, v0
    vadc.vvm v14, v8, v7, v0
    vadc.vvm v22, v11, v22, v0
    vadc.vvm v4, v21, v23, v0
    vadc.vvm v26, v26, v6, v0
    vadc.vvm v24, v31, v14, v0
    vadc.vvm v1, v29, v21, v0
    vadc.vvm v18, v1, v24, v0
    vadc.vvm v27, v20, v31, v0
    vadc.vvm v10, v29, v31, v0
    vadc.vxm v19, v9, x16, v0
    vadc.vxm v4, v3, x19, v0
    vadc.vxm v25, v22, x11, v0
    vadc.vxm v3, v0, x13, v0
    vadc.vxm v8, v2, x31, v0
    vadc.vxm v1, v16, x21, v0
    vadc.vxm v30, v14, x12, v0
    vadc.vxm v28, v18, x15, v0
    vadc.vxm v7, v25, x3, v0
    vadc.vxm v0, v21, x14, v0
    vadc.vxm v23, v11, x13, v0
    vadc.vxm v7, v8, x4, v0
    vadc.vxm v9, v8, x25, v0
    vadc.vxm v19, v22, x21, v0
    vadc.vxm v0, v23, x0, v0
    vadc.vim v28, v22, 8, v0
    vadc.vim v16, v18, 8, v0
    vadc.vim v9, v10, 8, v0
    vadc.vim v21, v0, 8, v0
    vadc.vim v31, v17, 8, v0
    vadc.vim v19, v2, 8, v0
    vadc.vim v3, v6, 8, v0
    vadc.vim v26, v4, 8, v0
    vadc.vim v8, v5, 8, v0
    vadc.vim v1, v24, 8, v0
    vadc.vim v13, v28, 8, v0
    vadc.vim v6, v14, 8, v0
    vadc.vim v7, v30, 8, v0
    vadc.vim v6, v17, 8, v0
    vadc.vim v0, v4, 8, v0
    vmadc.vv v25, v20, v26
    vmadc.vv v31, v29, v3
    vmadc.vv v7, v0, v25
    vmadc.vv v24, v28, v14
    vmadc.vv v0, v13, v8
    vmadc.vv v24, v31, v8
    vmadc.vv v22, v18, v5
    vmadc.vv v25, v7, v25
    vmadc.vv v11, v5, v3
    vmadc.vv v23, v31, v0
    vmadc.vv v4, v29, v19
    vmadc.vv v10, v16, v10
    vmadc.vv v10, v15, v6
    vmadc.vv v27, v8, v28
    vmadc.vv v14, v21, v23
    vmadc.vx v31, v0, x28
    vmadc.vx v2, v18, x15
    vmadc.vx v8, v30, x2
    vmadc.vx v10, v25, x11
    vmadc.vx v0, v18, x28
    vmadc.vx v15, v7, x20
    vmadc.vx v28, v22, x31
    vmadc.vx v10, v10, x7
    vmadc.vx v28, v25, x13
    vmadc.vx v12, v16, x28
    vmadc.vx v1, v19, x2
    vmadc.vx v12, v16, x0
    vmadc.vx v3, v20, x0
    vmadc.vx v18, v19, x6
    vmadc.vx v1, v27, x2
    vmadc.vi v17, v16, 8
    vmadc.vi v5, v4, 8
    vmadc.vi v0, v15, 8
    vmadc.vi v8, v21, 8
    vmadc.vi v5, v10, 8
    vmadc.vi v28, v24, 8
    vmadc.vi v6, v31, 8
    vmadc.vi v7, v22, 8
    vmadc.vi v10, v8, 8
    vmadc.vi v17, v9, 8
    vmadc.vi v5, v9, 8
    vmadc.vi v4, v9, 8
    vmadc.vi v19, v13, 8
    vmadc.vi v6, v15, 8
    vmadc.vi v30, v22, 8
    vsbc.vvm v28, v29, v6, v0
    vsbc.vvm v5, v19, v11, v0
    vsbc.vvm v1, v2, v26, v0
    vsbc.vvm v22, v31, v15, v0
    vsbc.vvm v12, v11, v28, v0
    vsbc.vvm v10, v24, v23, v0
    vsbc.vvm v11, v10, v26, v0
    vsbc.vvm v0, v26, v17, v0
    vsbc.vvm v10, v19, v10, v0
    vsbc.vvm v15, v25, v1, v0
    vsbc.vvm v31, v11, v15, v0
    vsbc.vvm v29, v17, v23, v0
    vsbc.vvm v27, v30, v5, v0
    vsbc.vvm v28, v18, v10, v0
    vsbc.vvm v8, v6, v8, v0
    vsbc.vxm v18, v9, x8, v0
    vsbc.vxm v24, v24, x29, v0
    vsbc.vxm v5, v12, x7, v0
    vsbc.vxm v8, v17, x18, v0
    vsbc.vxm v5, v12, x23, v0
    vsbc.vxm v25, v10, x16, v0
    vsbc.vxm v17, v16, x8, v0
    vsbc.vxm v24, v0, x28, v0
    vsbc.vxm v8, v10, x8, v0
    vsbc.vxm v14, v26, x18, v0
    vsbc.vxm v14, v27, x7, v0
    vsbc.vxm v6, v28, x24, v0
    vsbc.vxm v23, v7, x15, v0
    vsbc.vxm v14, v4, x14, v0
    vsbc.vxm v16, v9, x27, v0
    vmsbc.vv v3, v4, v22
    vmsbc.vv v20, v20, v0
    vmsbc.vv v12, v18, v28
    vmsbc.vv v9, v25, v24
    vmsbc.vv v17, v3, v15
    vmsbc.vv v29, v28, v8
    vmsbc.vv v2, v17, v12
    vmsbc.vv v21, v18, v27
    vmsbc.vv v16, v10, v7
    vmsbc.vv v5, v9, v20
    vmsbc.vv v19, v22, v6
    vmsbc.vv v30, v17, v11
    vmsbc.vv v4, v8, v0
    vmsbc.vv v31, v15, v10
    vmsbc.vv v16, v1, v9
    vmsbc.vx v9, v27, x12
    vmsbc.vx v31, v1, x11
    vmsbc.vx v21, v17, x11
    vmsbc.vx v13, v13, x8
    vmsbc.vx v10, v8, x15
    vmsbc.vx v12, v1, x4
    vmsbc.vx v24, v8, x20
    vmsbc.vx v2, v28, x30
    vmsbc.vx v26, v21, x15
    vmsbc.vx v25, v16, x3
    vmsbc.vx v20, v11, x16
    vmsbc.vx v21, v20, x26
    vmsbc.vx v30, v30, x15
    vmsbc.vx v16, v2, x13
    vmsbc.vx v25, v25, x28
    vmerge.vvm v1, v11, v7, v0
    vmerge.vvm v1, v28, v9, v0
    vmerge.vvm v0, v27, v27, v0
    vmerge.vvm v27, v22, v16, v0
    vmerge.vvm v8, v15, v18, v0
    vmerge.vvm v20, v15, v6, v0
    vmerge.vvm v21, v16, v0, v0
    vmerge.vvm v8, v25, v23, v0
    vmerge.vvm v19, v18, v20, v0
    vmerge.vvm v10, v15, v22, v0
    vmerge.vvm v23, v10, v31, v0
    vmerge.vvm v18, v9, v4, v0
    vmerge.vvm v0, v18, v26, v0
    vmerge.vvm v5, v27, v26, v0
    vmerge.vvm v31, v9, v21, v0
    vmerge.vxm v8, v1, x29, v0
    vmerge.vxm v3, v20, x6, v0
    vmerge.vxm v28, v30, x25, v0
    vmerge.vxm v24, v5, x13, v0
    vmerge.vxm v5, v19, x29, v0
    vmerge.vxm v29, v29, x30, v0
    vmerge.vxm v10, v9, x7, v0
    vmerge.vxm v1, v12, x26, v0
    vmerge.vxm v18, v6, x19, v0
    vmerge.vxm v8, v26, x2, v0
    vmerge.vxm v5, v20, x12, v0
    vmerge.vxm v27, v18, x22, v0
    vmerge.vxm v14, v23, x24, v0
    vmerge.vxm v21, v12, x4, v0
    vmerge.vxm v1, v7, x8, v0
    vmerge.vim v30, v11, 8, v0
    vmerge.vim v11, v20, 8, v0
    vmerge.vim v11, v4, 8, v0
    vmerge.vim v10, v2, 8, v0
    vmerge.vim v12, v9, 8, v0
    vmerge.vim v6, v11, 8, v0
    vmerge.vim v31, v12, 8, v0
    vmerge.vim v22, v6, 8, v0
    vmerge.vim v18, v30, 8, v0
    vmerge.vim v30, v2, 8, v0
    vmerge.vim v4, v8, 8, v0
    vmerge.vim v11, v2, 8, v0
    vmerge.vim v23, v15, 8, v0
    vmerge.vim v18, v22, 8, v0
    vmerge.vim v14, v20, 8, v0
    vmv.v.v v9, v11
    vmv.v.v v18, v14
    vmv.v.v v28, v16
    vmv.v.v v28, v26
    vmv.v.v v2, v23
    vmv.v.v v21, v25
    vmv.v.v v1, v18
    vmv.v.v v27, v22
    vmv.v.v v25, v26
    vmv.v.v v20, v22
    vmv.v.v v15, v23
    vmv.v.v v19, v25
    vmv.v.v v26, v11
    vmv.v.v v30, v18
    vmv.v.v v8, v11
    vmv.v.x v7, x20
    vmv.v.x v15, x6
    vmv.v.x v11, x7
    vmv.v.x v11, x9
    vmv.v.x v16, x9
    vmv.v.x v12, x4
    vmv.v.x v9, x0
    vmv.v.x v19, x3
    vmv.v.x v9, x20
    vmv.v.x v14, x24
    vmv.v.x v7, x26
    vmv.v.x v13, x3
    vmv.v.x v13, x23
    vmv.v.x v30, x18
    vmv.v.x v21, x4
    vmv.v.i v6, 3
    vmv.v.i v20, 3
    vmv.v.i v7, 3
    vmv.v.i v16, 3
    vmv.v.i v18, 3
    vmv.v.i v22, 3
    vmv.v.i v10, 3
    vmv.v.i v9, 3
    vmv.v.i v8, 3
    vmv.v.i v21, 3
    vmv.v.i v15, 3
    vmv.v.i v10, 3
    vmv.v.i v11, 3
    vmv.v.i v31, 3
    vmv.v.i v29, 3
    vmseq.vv v9, v28, v6
    vmseq.vv v14, v16, v29
    vmseq.vv v4, v10, v17
    vmseq.vv v8, v13, v8
    vmseq.vv v29, v10, v21
    vmseq.vv v29, v12, v25
    vmseq.vv v26, v14, v10
    vmseq.vv v12, v18, v23
    vmseq.vv v28, v1, v23
    vmseq.vv v26, v29, v17
    vmseq.vv v7, v29, v18
    vmseq.vv v23, v0, v2
    vmseq.vv v23, v19, v23
    vmseq.vv v31, v25, v20
    vmseq.vv v0, v7, v28
    vmseq.vx v13, v2, x14
    vmseq.vx v2, v2, x0
    vmseq.vx v9, v19, x9
    vmseq.vx v30, v25, x5
    vmseq.vx v21, v3, x0
    vmseq.vx v23, v13, x20
    vmseq.vx v27, v9, x21
    vmseq.vx v6, v7, x12
    vmseq.vx v16, v27, x3
    vmseq.vx v11, v16, x25
    vmseq.vx v6, v5, x4
    vmseq.vx v3, v19, x2
    vmseq.vx v7, v29, x14
    vmseq.vx v5, v1, x20
    vmseq.vx v3, v8, x3
    vmseq.vi v1, v10, 8
    vmseq.vi v17, v18, 8
    vmseq.vi v12, v24, 8
    vmseq.vi v25, v14, 8
    vmseq.vi v19, v24, 8
    vmseq.vi v24, v10, 8
    vmseq.vi v15, v17, 8
    vmseq.vi v2, v14, 8
    vmseq.vi v4, v19, 8
    vmseq.vi v28, v2, 8
    vmseq.vi v2, v22, 8
    vmseq.vi v14, v16, 8
    vmseq.vi v29, v0, 8
    vmseq.vi v1, v0, 8
    vmseq.vi v28, v19, 8
    vmsne.vv v27, v28, v1
    vmsne.vv v26, v27, v7
    vmsne.vv v28, v19, v0
    vmsne.vv v28, v11, v23
    vmsne.vv v4, v21, v29
    vmsne.vv v0, v16, v23
    vmsne.vv v5, v14, v21
    vmsne.vv v8, v3, v0
    vmsne.vv v8, v11, v28
    vmsne.vv v8, v9, v24
    vmsne.vv v30, v8, v5
    vmsne.vv v30, v18, v12
    vmsne.vv v12, v25, v19
    vmsne.vv v19, v1, v13
    vmsne.vv v13, v3, v20
    vmsne.vx v1, v12, x23
    vmsne.vx v15, v11, x26
    vmsne.vx v26, v12, x29
    vmsne.vx v0, v1, x5
    vmsne.vx v6, v20, x6
    vmsne.vx v24, v6, x13
    vmsne.vx v15, v31, x18
    vmsne.vx v26, v22, x6
    vmsne.vx v8, v9, x0
    vmsne.vx v29, v2, x16
    vmsne.vx v15, v1, x29
    vmsne.vx v29, v10, x25
    vmsne.vx v1, v3, x30
    vmsne.vx v14, v29, x27
    vmsne.vx v4, v2, x3
    vmsne.vi v4, v15, 8
    vmsne.vi v19, v27, 8
    vmsne.vi v27, v12, 8
    vmsne.vi v28, v23, 8
    vmsne.vi v30, v0, 8
    vmsne.vi v7, v8, 8
    vmsne.vi v21, v15, 8
    vmsne.vi v6, v2, 8
    vmsne.vi v21, v9, 8
    vmsne.vi v3, v2, 8
    vmsne.vi v25, v15, 8
    vmsne.vi v28, v20, 8
    vmsne.vi v22, v31, 8
    vmsne.vi v9, v31, 8
    vmsne.vi v10, v25, 8
    vmsltu.vv v30, v4, v5
    vmsltu.vv v17, v27, v27
    vmsltu.vv v2, v28, v1
    vmsltu.vv v7, v1, v17
    vmsltu.vv v18, v19, v9
    vmsltu.vv v14, v29, v17
    vmsltu.vv v21, v10, v25
    vmsltu.vv v7, v22, v7
    vmsltu.vv v31, v4, v4
    vmsltu.vv v20, v28, v28
    vmsltu.vv v24, v19, v18
    vmsltu.vv v28, v21, v24
    vmsltu.vv v27, v2, v2
    vmsltu.vv v21, v19, v6
    vmsltu.vv v10, v24, v25
    vmsltu.vx v13, v25, x14
    vmsltu.vx v18, v20, x4
    vmsltu.vx v1, v6, x31
    vmsltu.vx v12, v31, x19
    vmsltu.vx v6, v16, x13
    vmsltu.vx v20, v4, x28
    vmsltu.vx v14, v5, x8
    vmsltu.vx v4, v4, x4
    vmsltu.vx v16, v21, x2
    vmsltu.vx v18, v12, x14
    vmsltu.vx v23, v9, x0
    vmsltu.vx v27, v21, x17
    vmsltu.vx v9, v14, x23
    vmsltu.vx v6, v16, x6
    vmsltu.vx v5, v10, x29
    vmslt.vv v27, v31, v21
    vmslt.vv v29, v1, v24
    vmslt.vv v6, v30, v2
    vmslt.vv v24, v29, v3
    vmslt.vv v16, v8, v5
    vmslt.vv v22, v15, v5
    vmslt.vv v19, v5, v8
    vmslt.vv v17, v30, v7
    vmslt.vv v7, v23, v6
    vmslt.vv v0, v27, v11
    vmslt.vv v10, v0, v23
    vmslt.vv v8, v4, v16
    vmslt.vv v24, v13, v23
    vmslt.vv v26, v25, v7
    vmslt.vv v11, v19, v8
    vmslt.vx v2, v29, x15
    vmslt.vx v24, v10, x6
    vmslt.vx v12, v17, x15
    vmslt.vx v28, v15, x12
    vmslt.vx v20, v12, x24
    vmslt.vx v27, v31, x16
    vmslt.vx v26, v22, x25
    vmslt.vx v13, v2, x1
    vmslt.vx v15, v0, x5
    vmslt.vx v6, v14, x14
    vmslt.vx v9, v16, x11
    vmslt.vx v19, v29, x31
    vmslt.vx v8, v9, x8
    vmslt.vx v31, v16, x30
    vmslt.vx v26, v21, x10
    vmsleu.vv v25, v21, v17
    vmsleu.vv v4, v14, v27
    vmsleu.vv v6, v30, v7
    vmsleu.vv v3, v15, v20
    vmsleu.vv v24, v8, v9
    vmsleu.vv v2, v6, v8
    vmsleu.vv v26, v30, v3
    vmsleu.vv v17, v5, v22
    vmsleu.vv v15, v8, v14
    vmsleu.vv v15, v1, v14
    vmsleu.vv v6, v11, v22
    vmsleu.vv v25, v0, v3
    vmsleu.vv v28, v10, v18
    vmsleu.vv v4, v27, v16
    vmsleu.vv v11, v2, v3
    vmsleu.vx v9, v29, x5
    vmsleu.vx v30, v8, x1
    vmsleu.vx v3, v11, x12
    vmsleu.vx v8, v5, x15
    vmsleu.vx v31, v17, x13
    vmsleu.vx v7, v23, x16
    vmsleu.vx v8, v4, x1
    vmsleu.vx v10, v7, x0
    vmsleu.vx v11, v19, x8
    vmsleu.vx v28, v1, x22
    vmsleu.vx v17, v1, x24
    vmsleu.vx v22, v31, x7
    vmsleu.vx v19, v23, x0
    vmsleu.vx v11, v25, x18
    vmsleu.vx v24, v14, x26
    vmsleu.vi v28, v27, 8
    vmsleu.vi v20, v5, 8
    vmsleu.vi v21, v8, 8
    vmsleu.vi v12, v3, 8
    vmsleu.vi v24, v15, 8
    vmsleu.vi v6, v17, 8
    vmsleu.vi v27, v14, 8
    vmsleu.vi v20, v15, 8
    vmsleu.vi v14, v9, 8
    vmsleu.vi v27, v22, 8
    vmsleu.vi v18, v23, 8
    vmsleu.vi v6, v0, 8
    vmsleu.vi v2, v31, 8
    vmsleu.vi v27, v25, 8
    vmsleu.vi v31, v10, 8
    vmsle.vv v2, v16, v8
    vmsle.vv v27, v23, v11
    vmsle.vv v16, v28, v21
    vmsle.vv v6, v27, v17
    vmsle.vv v9, v15, v22
    vmsle.vv v14, v10, v8
    vmsle.vv v18, v0, v15
    vmsle.vv v2, v12, v6
    vmsle.vv v5, v11, v12
    vmsle.vv v1, v27, v13
    vmsle.vv v24, v5, v10
    vmsle.vv v14, v21, v6
    vmsle.vv v9, v24, v2
    vmsle.vv v25, v14, v20
    vmsle.vv v12, v1, v28
    vmsle.vx v19, v19, x21
    vmsle.vx v0, v30, x20
    vmsle.vx v12, v7, x24
    vmsle.vx v23, v22, x29
    vmsle.vx v17, v22, x21
    vmsle.vx v19, v24, x10
    vmsle.vx v27, v14, x9
    vmsle.vx v6, v16, x31
    vmsle.vx v23, v30, x5
    vmsle.vx v30, v7, x30
    vmsle.vx v15, v11, x31
    vmsle.vx v4, v13, x1
    vmsle.vx v31, v23, x27
    vmsle.vx v2, v19, x9
    vmsle.vx v31, v14, x30
    vmsle.vi v24, v2, 8
    vmsle.vi v0, v16, 8
    vmsle.vi v29, v7, 8
    vmsle.vi v2, v30, 8
    vmsle.vi v7, v5, 8
    vmsle.vi v19, v1, 8
    vmsle.vi v8, v31, 8
    vmsle.vi v26, v14, 8
    vmsle.vi v8, v0, 8
    vmsle.vi v31, v12, 8
    vmsle.vi v27, v14, 8
    vmsle.vi v17, v6, 8
    vmsle.vi v16, v10, 8
    vmsle.vi v6, v5, 8
    vmsle.vi v3, v12, 8
    vmsgtu.vx v1, v0, x19
    vmsgtu.vx v3, v5, x16
    vmsgtu.vx v22, v11, x13
    vmsgtu.vx v26, v23, x15
    vmsgtu.vx v6, v23, x6
    vmsgtu.vx v22, v17, x0
    vmsgtu.vx v21, v4, x2
    vmsgtu.vx v18, v12, x17
    vmsgtu.vx v28, v8, x3
    vmsgtu.vx v2, v27, x16
    vmsgtu.vx v25, v23, x16
    vmsgtu.vx v25, v29, x25
    vmsgtu.vx v7, v12, x28
    vmsgtu.vx v15, v21, x28
    vmsgtu.vx v4, v31, x15
    vmsgtu.vi v9, v31, 8
    vmsgtu.vi v16, v25, 8
    vmsgtu.vi v23, v29, 8
    vmsgtu.vi v23, v16, 8
    vmsgtu.vi v1, v2, 8
    vmsgtu.vi v31, v19, 8
    vmsgtu.vi v27, v17, 8
    vmsgtu.vi v31, v30, 8
    vmsgtu.vi v11, v13, 8
    vmsgtu.vi v23, v24, 8
    vmsgtu.vi v4, v27, 8
    vmsgtu.vi v6, v12, 8
    vmsgtu.vi v5, v19, 8
    vmsgtu.vi v0, v3, 8
    vmsgtu.vi v13, v20, 8
    vmsgt.vx v31, v12, x28
    vmsgt.vx v0, v13, x19
    vmsgt.vx v7, v12, x13
    vmsgt.vx v26, v29, x29
    vmsgt.vx v5, v11, x1
    vmsgt.vx v22, v7, x28
    vmsgt.vx v2, v13, x4
    vmsgt.vx v10, v0, x18
    vmsgt.vx v23, v24, x21
    vmsgt.vx v25, v16, x25
    vmsgt.vx v14, v28, x11
    vmsgt.vx v31, v15, x22
    vmsgt.vx v10, v21, x6
    vmsgt.vx v22, v17, x31
    vmsgt.vx v1, v20, x28
    vmsgt.vi v5, v20, 8
    vmsgt.vi v15, v18, 8
    vmsgt.vi v29, v16, 8
    vmsgt.vi v10, v30, 8
    vmsgt.vi v26, v5, 8
    vmsgt.vi v9, v2, 8
    vmsgt.vi v30, v4, 8
    vmsgt.vi v25, v20, 8
    vmsgt.vi v2, v14, 8
    vmsgt.vi v25, v28, 8
    vmsgt.vi v21, v11, 8
    vmsgt.vi v23, v30, 8
    vmsgt.vi v3, v30, 8
    vmsgt.vi v10, v25, 8
    vmsgt.vi v31, v26, 8
    vsaddu.vv v4, v26, v20
    vsaddu.vv v23, v6, v21
    vsaddu.vv v11, v16, v0
    vsaddu.vv v28, v16, v23
    vsaddu.vv v14, v8, v7
    vsaddu.vv v21, v14, v4
    vsaddu.vv v10, v30, v18
    vsaddu.vv v4, v4, v17
    vsaddu.vv v2, v18, v8
    vsaddu.vv v8, v6, v23
    vsaddu.vv v31, v27, v0
    vsaddu.vv v27, v3, v24
    vsaddu.vv v0, v9, v4
    vsaddu.vv v29, v20, v25
    vsaddu.vv v30, v0, v29
    vsaddu.vx v27, v28, x7
    vsaddu.vx v15, v10, x25
    vsaddu.vx v13, v28, x16
    vsaddu.vx v27, v26, x28
    vsaddu.vx v28, v18, x17
    vsaddu.vx v21, v15, x16
    vsaddu.vx v28, v18, x2
    vsaddu.vx v6, v8, x22
    vsaddu.vx v21, v14, x3
    vsaddu.vx v14, v5, x11
    vsaddu.vx v30, v19, x2
    vsaddu.vx v29, v26, x0
    vsaddu.vx v8, v13, x28
    vsaddu.vx v26, v5, x31
    vsaddu.vx v28, v14, x7
    vsaddu.vi v21, v1, 8
    vsaddu.vi v27, v28, 8
    vsaddu.vi v4, v23, 8
    vsaddu.vi v24, v20, 8
    vsaddu.vi v7, v6, 8
    vsaddu.vi v23, v21, 8
    vsaddu.vi v22, v6, 8
    vsaddu.vi v18, v11, 8
    vsaddu.vi v6, v27, 8
    vsaddu.vi v19, v11, 8
    vsaddu.vi v22, v4, 8
    vsaddu.vi v28, v4, 8
    vsaddu.vi v5, v20, 8
    vsaddu.vi v25, v29, 8
    vsaddu.vi v26, v1, 8
    vsadd.vv v31, v3, v11
    vsadd.vv v7, v0, v27
    vsadd.vv v27, v15, v14
    vsadd.vv v3, v26, v28
    vsadd.vv v4, v11, v12
    vsadd.vv v9, v20, v22
    vsadd.vv v29, v30, v19
    vsadd.vv v9, v21, v25
    vsadd.vv v1, v19, v11
    vsadd.vv v17, v11, v27
    vsadd.vv v28, v6, v8
    vsadd.vv v9, v9, v31
    vsadd.vv v29, v7, v30
    vsadd.vv v19, v14, v30
    vsadd.vv v11, v27, v11
    vsadd.vx v1, v22, x12
    vsadd.vx v28, v10, x14
    vsadd.vx v21, v29, x14
    vsadd.vx v7, v23, x16
    vsadd.vx v30, v16, x20
    vsadd.vx v2, v25, x31
    vsadd.vx v4, v14, x30
    vsadd.vx v17, v26, x8
    vsadd.vx v30, v5, x22
    vsadd.vx v27, v24, x26
    vsadd.vx v12, v2, x25
    vsadd.vx v18, v19, x8
    vsadd.vx v17, v8, x20
    vsadd.vx v20, v13, x6
    vsadd.vx v15, v8, x15
    vsadd.vi v7, v21, 8
    vsadd.vi v10, v23, 8
    vsadd.vi v31, v6, 8
    vsadd.vi v15, v25, 8
    vsadd.vi v24, v26, 8
    vsadd.vi v1, v12, 8
    vsadd.vi v11, v0, 8
    vsadd.vi v28, v6, 8
    vsadd.vi v9, v17, 8
    vsadd.vi v3, v14, 8
    vsadd.vi v19, v3, 8
    vsadd.vi v15, v13, 8
    vsadd.vi v29, v9, 8
    vsadd.vi v11, v7, 8
    vsadd.vi v17, v6, 8
    vssubu.vv v17, v4, v25
    vssubu.vv v16, v15, v7
    vssubu.vv v28, v18, v15
    vssubu.vv v11, v5, v8
    vssubu.vv v18, v21, v0
    vssubu.vv v1, v26, v17
    vssubu.vv v4, v18, v2
    vssubu.vv v29, v25, v0
    vssubu.vv v26, v2, v7
    vssubu.vv v30, v14, v17
    vssubu.vv v1, v26, v1
    vssubu.vv v7, v26, v15
    vssubu.vv v20, v24, v15
    vssubu.vv v15, v30, v16
    vssubu.vv v18, v0, v24
    vssubu.vx v0, v15, x4
    vssubu.vx v1, v13, x21
    vssubu.vx v15, v21, x2
    vssubu.vx v12, v8, x0
    vssubu.vx v27, v31, x17
    vssubu.vx v26, v21, x23
    vssubu.vx v15, v20, x30
    vssubu.vx v24, v13, x14
    vssubu.vx v31, v22, x27
    vssubu.vx v29, v9, x15
    vssubu.vx v26, v16, x9
    vssubu.vx v7, v7, x2
    vssubu.vx v25, v6, x25
    vssubu.vx v29, v16, x30
    vssubu.vx v27, v7, x29
    vssub.vv v16, v6, v7
    vssub.vv v6, v22, v30
    vssub.vv v28, v21, v15
    vssub.vv v24, v4, v6
    vssub.vv v17, v30, v4
    vssub.vv v13, v5, v2
    vssub.vv v25, v17, v2
    vssub.vv v18, v19, v28
    vssub.vv v20, v5, v31
    vssub.vv v31, v11, v5
    vssub.vv v27, v16, v0
    vssub.vv v24, v1, v13
    vssub.vv v24, v23, v10
    vssub.vv v20, v1, v22
    vssub.vv v17, v7, v0
    vssub.vx v11, v21, x3
    vssub.vx v30, v27, x18
    vssub.vx v2, v21, x31
    vssub.vx v10, v21, x26
    vssub.vx v23, v18, x22
    vssub.vx v4, v23, x23
    vssub.vx v14, v15, x26
    vssub.vx v23, v4, x22
    vssub.vx v24, v17, x2
    vssub.vx v8, v25, x9
    vssub.vx v21, v30, x2
    vssub.vx v10, v3, x25
    vssub.vx v28, v26, x10
    vssub.vx v23, v19, x25
    vssub.vx v5, v27, x1
    vsll.vv v0, v22, v9
    vsll.vv v11, v22, v8
    vsll.vv v14, v10, v31
    vsll.vv v16, v20, v4
    vsll.vv v7, v6, v8
    vsll.vv v6, v17, v7
    vsll.vv v3, v16, v20
    vsll.vv v25, v16, v24
    vsll.vv v4, v29, v10
    vsll.vv v31, v30, v25
    vsll.vv v4, v27, v9
    vsll.vv v2, v22, v4
    vsll.vv v5, v23, v27
    vsll.vv v3, v9, v0
    vsll.vv v31, v23, v9
    vsll.vx v27, v4, x17
    vsll.vx v7, v13, x31
    vsll.vx v15, v16, x28
    vsll.vx v10, v8, x29
    vsll.vx v29, v28, x25
    vsll.vx v16, v8, x15
    vsll.vx v18, v9, x24
    vsll.vx v31, v2, x14
    vsll.vx v18, v16, x25
    vsll.vx v3, v14, x8
    vsll.vx v15, v3, x17
    vsll.vx v20, v12, x30
    vsll.vx v20, v14, x6
    vsll.vx v18, v23, x24
    vsll.vx v27, v27, x10
    vsll.vi v16, v21, 8
    vsll.vi v22, v12, 8
    vsll.vi v8, v12, 8
    vsll.vi v14, v6, 8
    vsll.vi v22, v29, 8
    vsll.vi v27, v27, 8
    vsll.vi v10, v23, 8
    vsll.vi v14, v12, 8
    vsll.vi v16, v15, 8
    vsll.vi v24, v9, 8
    vsll.vi v9, v14, 8
    vsll.vi v5, v8, 8
    vsll.vi v7, v26, 8
    vsll.vi v1, v8, 8
    vsll.vi v24, v2, 8
    vsmul.vv v5, v26, v26
    vsmul.vv v29, v23, v12
    vsmul.vv v26, v16, v8
    vsmul.vv v6, v29, v26
    vsmul.vv v23, v2, v8
    vsmul.vv v13, v0, v15
    vsmul.vv v5, v19, v18
    vsmul.vv v20, v11, v14
    vsmul.vv v2, v0, v3
    vsmul.vv v19, v27, v3
    vsmul.vv v19, v2, v30
    vsmul.vv v18, v7, v17
    vsmul.vv v28, v25, v2
    vsmul.vv v17, v20, v2
    vsmul.vv v17, v15, v8
    vsmul.vx v0, v16, x24
    vsmul.vx v27, v0, x25
    vsmul.vx v14, v23, x10
    vsmul.vx v10, v13, x8
    vsmul.vx v29, v7, x13
    vsmul.vx v27, v12, x4
    vsmul.vx v6, v20, x14
    vsmul.vx v18, v31, x25
    vsmul.vx v8, v30, x28
    vsmul.vx v21, v21, x21
    vsmul.vx v30, v3, x10
    vsmul.vx v11, v9, x23
    vsmul.vx v20, v7, x25
    vsmul.vx v6, v16, x19
    vsmul.vx v27, v12, x23
    vsrl.vv v19, v0, v13
    vsrl.vv v24, v3, v28
    vsrl.vv v12, v9, v30
    vsrl.vv v27, v15, v11
    vsrl.vv v23, v30, v6
    vsrl.vv v16, v22, v31
    vsrl.vv v15, v24, v10
    vsrl.vv v17, v8, v7
    vsrl.vv v16, v21, v1
    vsrl.vv v20, v3, v24
    vsrl.vv v25, v3, v12
    vsrl.vv v24, v6, v6
    vsrl.vv v11, v22, v19
    vsrl.vv v27, v17, v30
    vsrl.vv v8, v19, v29
    vsrl.vx v6, v0, x29
    vsrl.vx v15, v9, x12
    vsrl.vx v5, v28, x8
    vsrl.vx v8, v19, x21
    vsrl.vx v15, v15, x18
    vsrl.vx v1, v26, x30
    vsrl.vx v25, v19, x10
    vsrl.vx v20, v2, x28
    vsrl.vx v8, v25, x1
    vsrl.vx v2, v22, x11
    vsrl.vx v28, v31, x30
    vsrl.vx v9, v6, x27
    vsrl.vx v17, v6, x21
    vsrl.vx v6, v6, x19
    vsrl.vx v20, v1, x7
    vsrl.vi v24, v15, 8
    vsrl.vi v11, v10, 8
    vsrl.vi v14, v6, 8
    vsrl.vi v3, v3, 8
    vsrl.vi v12, v27, 8
    vsrl.vi v22, v3, 8
    vsrl.vi v31, v29, 8
    vsrl.vi v21, v5, 8
    vsrl.vi v16, v26, 8
    vsrl.vi v28, v6, 8
    vsrl.vi v24, v11, 8
    vsrl.vi v3, v19, 8
    vsrl.vi v15, v19, 8
    vsrl.vi v23, v2, 8
    vsrl.vi v27, v5, 8
    vsra.vv v9, v7, v14
    vsra.vv v29, v19, v26
    vsra.vv v12, v21, v20
    vsra.vv v27, v1, v21
    vsra.vv v31, v6, v26
    vsra.vv v25, v25, v19
    vsra.vv v2, v0, v4
    vsra.vv v17, v13, v12
    vsra.vv v16, v31, v25
    vsra.vv v25, v22, v14
    vsra.vv v10, v2, v16
    vsra.vv v5, v14, v31
    vsra.vv v22, v5, v26
    vsra.vv v30, v6, v10
    vsra.vv v31, v31, v12
    vsra.vx v13, v6, x12
    vsra.vx v27, v27, x28
    vsra.vx v25, v20, x4
    vsra.vx v19, v10, x11
    vsra.vx v17, v0, x11
    vsra.vx v0, v9, x16
    vsra.vx v29, v12, x8
    vsra.vx v22, v30, x17
    vsra.vx v19, v24, x19
    vsra.vx v25, v0, x19
    vsra.vx v18, v11, x21
    vsra.vx v24, v10, x8
    vsra.vx v25, v0, x14
    vsra.vx v27, v22, x3
    vsra.vx v22, v20, x3
    vsra.vi v25, v18, 8
    vsra.vi v22, v19, 8
    vsra.vi v31, v11, 8
    vsra.vi v25, v23, 8
    vsra.vi v0, v25, 8
    vsra.vi v13, v20, 8
    vsra.vi v26, v23, 8
    vsra.vi v27, v19, 8
    vsra.vi v30, v20, 8
    vsra.vi v30, v17, 8
    vsra.vi v25, v11, 8
    vsra.vi v30, v26, 8
    vsra.vi v26, v5, 8
    vsra.vi v12, v7, 8
    vsra.vi v29, v17, 8
    vssrl.vv v22, v4, v22
    vssrl.vv v26, v26, v15
    vssrl.vv v27, v1, v10
    vssrl.vv v14, v26, v2
    vssrl.vv v6, v23, v12
    vssrl.vv v3, v12, v0
    vssrl.vv v3, v9, v16
    vssrl.vv v18, v2, v25
    vssrl.vv v25, v12, v21
    vssrl.vv v31, v2, v3
    vssrl.vv v21, v21, v17
    vssrl.vv v27, v21, v15
    vssrl.vv v8, v28, v2
    vssrl.vv v8, v20, v17
    vssrl.vv v19, v10, v22
    vssrl.vx v26, v28, x11
    vssrl.vx v26, v6, x9
    vssrl.vx v0, v30, x0
    vssrl.vx v4, v20, x18
    vssrl.vx v30, v0, x1
    vssrl.vx v16, v16, x31
    vssrl.vx v12, v17, x17
    vssrl.vx v11, v9, x19
    vssrl.vx v19, v8, x15
    vssrl.vx v18, v10, x30
    vssrl.vx v20, v12, x2
    vssrl.vx v27, v4, x12
    vssrl.vx v8, v18, x26
    vssrl.vx v7, v4, x19
    vssrl.vx v15, v29, x23
    vssrl.vi v6, v4, 8
    vssrl.vi v28, v20, 8
    vssrl.vi v27, v4, 8
    vssrl.vi v14, v21, 8
    vssrl.vi v1, v31, 8
    vssrl.vi v27, v12, 8
    vssrl.vi v24, v22, 8
    vssrl.vi v26, v6, 8
    vssrl.vi v13, v25, 8
    vssrl.vi v1, v5, 8
    vssrl.vi v22, v4, 8
    vssrl.vi v16, v23, 8
    vssrl.vi v12, v1, 8
    vssrl.vi v28, v27, 8
    vssrl.vi v0, v8, 8
    vssra.vv v6, v7, v31
    vssra.vv v19, v10, v7
    vssra.vv v0, v9, v18
    vssra.vv v23, v22, v5
    vssra.vv v29, v29, v9
    vssra.vv v21, v15, v19
    vssra.vv v14, v29, v5
    vssra.vv v11, v5, v18
    vssra.vv v27, v28, v23
    vssra.vv v13, v20, v1
    vssra.vv v25, v18, v26
    vssra.vv v16, v31, v31
    vssra.vv v1, v30, v22
    vssra.vv v24, v28, v28
    vssra.vv v9, v17, v4
    vssra.vx v30, v22, x31
    vssra.vx v26, v29, x2
    vssra.vx v29, v22, x3
    vssra.vx v16, v16, x15
    vssra.vx v2, v12, x23
    vssra.vx v8, v26, x25
    vssra.vx v10, v26, x7
    vssra.vx v18, v21, x23
    vssra.vx v4, v10, x2
    vssra.vx v10, v28, x15
    vssra.vx v20, v8, x18
    vssra.vx v3, v31, x14
    vssra.vx v23, v22, x26
    vssra.vx v4, v19, x10
    vssra.vx v24, v8, x8
    vssra.vi v2, v19, 8
    vssra.vi v15, v1, 8
    vssra.vi v9, v10, 8
    vssra.vi v26, v6, 8
    vssra.vi v3, v13, 8
    vssra.vi v12, v0, 8
    vssra.vi v23, v29, 8
    vssra.vi v29, v25, 8
    vssra.vi v12, v25, 8
    vssra.vi v24, v18, 8
    vssra.vi v29, v19, 8
    vssra.vi v16, v29, 8
    vssra.vi v23, v13, 8
    vssra.vi v13, v31, 8
    vssra.vi v7, v25, 8
    vnsrl.wv v28, v6, v22
    vnsrl.wv v22, v17, v20
    vnsrl.wv v27, v14, v3
    vnsrl.wv v29, v25, v1
    vnsrl.wv v12, v3, v6
    vnsrl.wv v7, v5, v8
    vnsrl.wv v15, v2, v7
    vnsrl.wv v24, v23, v17
    vnsrl.wv v24, v29, v2
    vnsrl.wv v31, v11, v11
    vnsrl.wv v17, v0, v6
    vnsrl.wv v19, v24, v12
    vnsrl.wv v14, v18, v8
    vnsrl.wv v3, v22, v19
    vnsrl.wv v11, v3, v8
    vnsrl.wx v31, v26, x8
    vnsrl.wx v5, v6, x31
    vnsrl.wx v23, v15, x20
    vnsrl.wx v19, v26, x4
    vnsrl.wx v20, v30, x10
    vnsrl.wx v17, v24, x1
    vnsrl.wx v13, v24, x26
    vnsrl.wx v27, v4, x21
    vnsrl.wx v11, v27, x31
    vnsrl.wx v4, v15, x28
    vnsrl.wx v9, v1, x26
    vnsrl.wx v16, v26, x0
    vnsrl.wx v17, v18, x27
    vnsrl.wx v18, v9, x20
    vnsrl.wx v18, v18, x27
    vnsrl.wi v28, v9, 8
    vnsrl.wi v24, v26, 8
    vnsrl.wi v12, v3, 8
    vnsrl.wi v26, v3, 8
    vnsrl.wi v15, v11, 8
    vnsrl.wi v7, v24, 8
    vnsrl.wi v27, v28, 8
    vnsrl.wi v10, v14, 8
    vnsrl.wi v18, v9, 8
    vnsrl.wi v30, v7, 8
    vnsrl.wi v25, v27, 8
    vnsrl.wi v6, v1, 8
    vnsrl.wi v31, v5, 8
    vnsrl.wi v6, v2, 8
    vnsrl.wi v31, v14, 8
    vnsra.wv v5, v18, v20
    vnsra.wv v14, v1, v12
    vnsra.wv v6, v3, v14
    vnsra.wv v16, v27, v28
    vnsra.wv v0, v4, v6
    vnsra.wv v0, v23, v2
    vnsra.wv v20, v16, v20
    vnsra.wv v17, v25, v14
    vnsra.wv v11, v15, v12
    vnsra.wv v0, v5, v9
    vnsra.wv v25, v5, v13
    vnsra.wv v6, v9, v6
    vnsra.wv v4, v4, v25
    vnsra.wv v25, v19, v10
    vnsra.wv v24, v31, v7
    vnsra.wx v2, v30, x5
    vnsra.wx v5, v11, x21
    vnsra.wx v22, v24, x8
    vnsra.wx v19, v30, x12
    vnsra.wx v26, v6, x0
    vnsra.wx v7, v7, x1
    vnsra.wx v7, v12, x28
    vnsra.wx v8, v22, x23
    vnsra.wx v9, v22, x0
    vnsra.wx v20, v23, x5
    vnsra.wx v11, v17, x4
    vnsra.wx v18, v7, x5
    vnsra.wx v29, v15, x27
    vnsra.wx v6, v16, x29
    vnsra.wx v7, v0, x26
    vnsra.wi v3, v16, 8
    vnsra.wi v7, v25, 8
    vnsra.wi v27, v30, 8
    vnsra.wi v1, v18, 8
    vnsra.wi v4, v5, 8
    vnsra.wi v17, v6, 8
    vnsra.wi v20, v7, 8
    vnsra.wi v22, v9, 8
    vnsra.wi v12, v10, 8
    vnsra.wi v7, v21, 8
    vnsra.wi v22, v13, 8
    vnsra.wi v23, v0, 8
    vnsra.wi v8, v2, 8
    vnsra.wi v15, v18, 8
    vnsra.wi v16, v18, 8
    vnclipu.wv v25, v13, v6
    vnclipu.wv v14, v1, v27
    vnclipu.wv v15, v19, v6
    vnclipu.wv v27, v22, v29
    vnclipu.wv v5, v26, v28
    vnclipu.wv v31, v12, v16
    vnclipu.wv v9, v11, v19
    vnclipu.wv v9, v11, v0
    vnclipu.wv v16, v21, v15
    vnclipu.wv v22, v17, v12
    vnclipu.wv v22, v9, v21
    vnclipu.wv v13, v28, v25
    vnclipu.wv v6, v4, v6
    vnclipu.wv v24, v2, v0
    vnclipu.wv v6, v30, v29
    vnclipu.wx v1, v30, x20
    vnclipu.wx v8, v7, x9
    vnclipu.wx v23, v18, x20
    vnclipu.wx v13, v18, x10
    vnclipu.wx v21, v24, x19
    vnclipu.wx v24, v27, x2
    vnclipu.wx v22, v4, x23
    vnclipu.wx v20, v6, x4
    vnclipu.wx v4, v11, x27
    vnclipu.wx v0, v29, x9
    vnclipu.wx v21, v16, x27
    vnclipu.wx v5, v24, x9
    vnclipu.wx v18, v17, x22
    vnclipu.wx v2, v14, x9
    vnclipu.wx v20, v6, x0
    vnclipu.wi v10, v20, 8
    vnclipu.wi v4, v18, 8
    vnclipu.wi v28, v29, 8
    vnclipu.wi v20, v6, 8
    vnclipu.wi v7, v22, 8
    vnclipu.wi v3, v13, 8
    vnclipu.wi v12, v26, 8
    vnclipu.wi v9, v3, 8
    vnclipu.wi v18, v29, 8
    vnclipu.wi v30, v15, 8
    vnclipu.wi v20, v21, 8
    vnclipu.wi v24, v7, 8
    vnclipu.wi v8, v6, 8
    vnclipu.wi v6, v19, 8
    vnclipu.wi v1, v7, 8
    vnclip.wv v2, v18, v12
    vnclip.wv v25, v2, v19
    vnclip.wv v22, v26, v4
    vnclip.wv v4, v14, v5
    vnclip.wv v12, v4, v27
    vnclip.wv v9, v31, v30
    vnclip.wv v27, v9, v4
    vnclip.wv v10, v4, v12
    vnclip.wv v19, v29, v2
    vnclip.wv v0, v31, v4
    vnclip.wv v3, v1, v18
    vnclip.wv v27, v26, v1
    vnclip.wv v8, v17, v18
    vnclip.wv v11, v5, v14
    vnclip.wv v1, v21, v25
    vnclip.wx v7, v22, x24
    vnclip.wx v27, v28, x10
    vnclip.wx v2, v21, x15
    vnclip.wx v24, v0, x1
    vnclip.wx v5, v19, x20
    vnclip.wx v18, v31, x10
    vnclip.wx v31, v0, x22
    vnclip.wx v30, v13, x12
    vnclip.wx v6, v1, x16
    vnclip.wx v17, v0, x18
    vnclip.wx v13, v17, x30
    vnclip.wx v20, v23, x24
    vnclip.wx v24, v20, x3
    vnclip.wx v1, v31, x10
    vnclip.wx v8, v11, x3
    vnclip.wi v29, v1, 8
    vnclip.wi v24, v18, 8
    vnclip.wi v26, v14, 8
    vnclip.wi v28, v6, 8
    vnclip.wi v13, v25, 8
    vnclip.wi v22, v10, 8
    vnclip.wi v15, v15, 8
    vnclip.wi v15, v27, 8
    vnclip.wi v14, v29, 8
    vnclip.wi v6, v0, 8
    vnclip.wi v14, v18, 8
    vnclip.wi v24, v30, 8
    vnclip.wi v26, v4, 8
    vnclip.wi v3, v12, 8
    vnclip.wi v25, v26, 8
    vwredsumu.vs v5, v25, v21
    vwredsumu.vs v11, v12, v22
    vwredsumu.vs v3, v4, v29
    vwredsumu.vs v20, v24, v26
    vwredsumu.vs v18, v11, v17
    vwredsumu.vs v7, v1, v14
    vwredsumu.vs v8, v0, v9
    vwredsumu.vs v13, v29, v27
    vwredsumu.vs v1, v19, v9
    vwredsumu.vs v21, v25, v20
    vwredsumu.vs v0, v20, v24
    vwredsumu.vs v3, v9, v31
    vwredsumu.vs v6, v26, v30
    vwredsumu.vs v15, v31, v11
    vwredsumu.vs v11, v0, v22
    vwredsum.vs v18, v2, v26
    vwredsum.vs v10, v17, v13
    vwredsum.vs v12, v1, v26
    vwredsum.vs v31, v19, v4
    vwredsum.vs v14, v6, v13
    vwredsum.vs v8, v10, v17
    vwredsum.vs v16, v9, v5
    vwredsum.vs v30, v29, v15
    vwredsum.vs v8, v5, v24
    vwredsum.vs v3, v30, v29
    vwredsum.vs v0, v15, v16
    vwredsum.vs v8, v15, v24
    vwredsum.vs v20, v17, v17
    vwredsum.vs v17, v8, v8
    vwredsum.vs v6, v8, v11
    li a7, 10
    ecall