name: Build artifact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  detect-files-changed:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Test files changed
        id: files-changed
        uses: tj-actions/changed-files@v44
        with:
          fetch_additional_submodule_history: 'true'
          files: |
            tests/ansibench/*
            tests/rv8-bench/*
            tests/*.c
      - name: Set alias
        id: has_files_changed
        run: |
          if [[ ${{ steps.files-changed.outputs.any_modified }} == true ]]; then
            echo "has_files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "has_files_changed=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      has_files_changed: ${{ steps.has_files_changed.outputs.has_files_changed }}

  build-artifact:
    needs: [detect-files-changed]
    if: ${{ needs.detect-files-changed.outputs.has_files_changed == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get upgrade -q -y
          sudo apt-get install -q -y gcc-multilib g++-multilib
          sudo apt-get install -q -y opam build-essential libgmp-dev z3 pkg-config zlib1g-dev
          .ci/riscv-toolchain-install.sh
          echo "$PWD/toolchain/bin" >> $GITHUB_PATH
      - name: Build binaries
        run: |
          make artifact ENABLE_PREBUILT=0
          mkdir -p /tmp/rv32emu-prebuilt
          mv build/linux-x86-softfp build/riscv32 /tmp/rv32emu-prebuilt
      - name: Build Sail model
        run: |
          cd /tmp
          opam init -y --disable-sandboxing
          opam switch create ocaml-base-compiler.4.06.1
          opam install sail -y
          eval $(opam config env)
          git clone https://github.com/riscv/sail-riscv.git
          cd sail-riscv
          git checkout 9547a30bf84572c458476591b569a95f5232c1c7
          ARCH=RV32 make -j
          mkdir -p /tmp/rv32emu-prebuilt/sail_cSim
          mv c_emulator/riscv_sim_RV32 /tmp/rv32emu-prebuilt/sail_cSim
      - name: Create tarball
        run: |
          cd /tmp
          tar -zcvf rv32emu-prebuilt.tar.gz rv32emu-prebuilt
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.RV32EMU_PREBUILT_TOKEN }}
        run: |
          RELEASE_TAG=$(date +'%Y.%m.%d')
          cd /tmp
          gh release create $RELEASE_TAG \
            --repo sysprog21/rv32emu-prebuilt \
            --title "$RELEASE_TAG""-nightly"
          gh release upload $RELEASE_TAG \
            rv32emu-prebuilt.tar.gz \
            --repo sysprog21/rv32emu-prebuilt
