name: Compliance Tests

on: [push, pull_request]

jobs:
  arch-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: |
           .ci/riscv-toolchain-install.sh
      shell: bash
    - name: architectural test
      run: |
           .ci/riscv-tests.sh
      shell: bash
