name: CI

on: [push, pull_request]

jobs:
  rv32emu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.0.2
    - name: install-dependencies
      run: | 
            sudo apt-get update
            sudo apt-get install libsdl2-dev
    - name: make
      run: make
    - name: make check
      run: make check

  coding_style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.0.2
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            sh .ci/check-format.sh
      shell: bash
