name: CI

on: [push, pull_request]

jobs:
  rv32emu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: |
            sudo apt-get update
            sudo apt-get install libsdl2-dev libsdl2-mixer-dev
            .ci/riscv-toolchain-install.sh
      shell: bash
    - name: default build
      run: make
    - name: check + tests
      run: |
            make check
            make tests
            make misalign
            make tool
            make distclean ENABLE_ARC=1 tests
    - name: diverse configurations
      run: |
            make distclean ENABLE_EXT_M=0 check
            make distclean ENABLE_EXT_A=0 check
            make distclean ENABLE_EXT_C=0 check
            make distclean ENABLE_EXT_F=0 check
            make distclean ENABLE_SDL=0 check
    - name: gdbstub test
      run: |
            make distclean ENABLE_GDBSTUB=1 gdbstub-test

  coding-style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            .ci/check-newline.sh
            .ci/check-format.sh
      shell: bash
